CREATE TABLE "BILL"
(
    "LOAN_NO" VARCHAR2(20) NOT NULL,
    "EO_SEQ" VARCHAR2(5) NOT NULL,
    "BILL_KIND" VARCHAR2(9),
    "BILL_NO" VARCHAR2(30),
    "BILL_ISS_DATE" VARCHAR2(8),
    "BILL_SUP_DATE" VARCHAR2(8),
    "BILL_SET_DATE" VARCHAR2(8),
    "BILL_STATUS" VARCHAR2(9),
    "ENTRY_DATE" VARCHAR2(8)
);
CREATE UNIQUE INDEX "PK_BILL" ON "BILL" ("LOAN_NO", "EO_SEQ");
----COMMENT ADD START----
COMMENT ON TABLE BILL IS '청구서' ;

COMMENT ON COLUMN BILL.LOAN_NO IS '회사코드';
COMMENT ON COLUMN BILL.EO_SEQ IS '회계기준코드';
COMMENT ON COLUMN BILL.BILL_KIND IS '회기';
COMMENT ON COLUMN BILL.BILL_NO IS '발생한도';
COMMENT ON COLUMN BILL.BILL_ISS_DATE IS '최종한도';
COMMENT ON COLUMN BILL.BILL_SUP_DATE IS '생성계정';
COMMENT ON COLUMN BILL.BILL_SET_DATE IS '생성일자';
COMMENT ON COLUMN BILL.BILL_STATUS IS '생성단말번호';
COMMENT ON COLUMN BILL.ENTRY_DATE IS '변경사용자계정';

DROP TABLE BILL;

SELECT * FROM BILL;
----COMMENT ADD END----

CREATE TABLE "CM_APPR"
(
    "APPR_KEY" VARCHAR2(60) NOT NULL,
    "SEQ" NUMBER(3,0),
    "APPR_CD" VARCHAR2(6),
    "APPR_SEQ" NUMBER(5,0),
    "MAIN_TAB" VARCHAR2(50),
    "COL0" VARCHAR2(50),
    "COL1" VARCHAR2(50),
    "COL2" VARCHAR2(50),
    "COL3" VARCHAR2(50),
    "COL4" VARCHAR2(50),
    "COL5" VARCHAR2(50),
    "COL6" VARCHAR2(50),
    "COL7" VARCHAR2(50),
    "COL8" VARCHAR2(50),
    "COL9" VARCHAR2(50),
    "REQ_ID" VARCHAR2(10),
    "REQ_ATHR_CD" VARCHAR2(8),
    "RES_ID" VARCHAR2(10),
    "RES_ATHR_CD" VARCHAR2(8),
    "REQ_DT" VARCHAR2(8),
    "REQ_DTM" VARCHAR2(6),
    "RES_DT" VARCHAR2(8),
    "RES_DTM" VARCHAR2(6),
    "APPR_ETC" VARCHAR2(4000),
    "AGN_PROC_STS" VARCHAR2(10),
    "APPR_BRCH" VARCHAR2(10)
);
CREATE UNIQUE INDEX "CM_APPR_PK" ON "CM_APPR" ("APPR_KEY");
----COMMENT ADD START----
COMMENT ON TABLE CM_APPR IS '청구서' ;

COMMENT ON COLUMN CM_APPR.APPR_KEY IS '회사코드';
COMMENT ON COLUMN CM_APPR.SEQ IS '회계기준코드';
COMMENT ON COLUMN CM_APPR.APPR_CD IS '회기';
COMMENT ON COLUMN CM_APPR.APPR_SEQ IS '발생한도';
COMMENT ON COLUMN CM_APPR.MAIN_TAB IS '최종한도';
COMMENT ON COLUMN CM_APPR.COL0 IS '생성계정';
COMMENT ON COLUMN CM_APPR.COL1 IS '생성일자';
COMMENT ON COLUMN CM_APPR.COL2 IS '생성단말번호';
COMMENT ON COLUMN CM_APPR.COL3 IS '변경사용자계정';
COMMENT ON COLUMN CM_APPR.COL4 IS '회사코드';
COMMENT ON COLUMN CM_APPR.COL5 IS '회계기준코드';
COMMENT ON COLUMN CM_APPR.COL6 IS '회기';
COMMENT ON COLUMN CM_APPR.COL7 IS '발생한도';
COMMENT ON COLUMN CM_APPR.COL8 IS '최종한도';
COMMENT ON COLUMN CM_APPR.COL9 IS '생성계정';
COMMENT ON COLUMN CM_APPR.REQ_ID IS '생성일자';
COMMENT ON COLUMN CM_APPR.REQ_ATHR_CD IS '생성단말번호';
COMMENT ON COLUMN CM_APPR.RES_ID IS '변경사용자계정';
COMMENT ON COLUMN CM_APPR.RES_ATHR_CD IS '회사코드';
COMMENT ON COLUMN CM_APPR.REQ_DT IS '회계기준코드';
COMMENT ON COLUMN CM_APPR.REQ_DTM IS '회기';
COMMENT ON COLUMN CM_APPR.RES_DT IS '발생한도';
COMMENT ON COLUMN CM_APPR.RES_DTM IS '최종한도';
COMMENT ON COLUMN CM_APPR.APPR_ETC IS '생성계정';
COMMENT ON COLUMN CM_APPR.AGN_PROC_STS IS '생성일자';
COMMENT ON COLUMN CM_APPR.APPR_BRCH IS '생성단말번호';

DROP TABLE CM_APPR;

SELECT * FROM CM_APPR;
----COMMENT ADD END----


CREATE TABLE "CM_APPR_ATHR"
(
    "APPR_ATHR_CD" VARCHAR2(5) NOT NULL,
    "APPR_ATHR_NM" VARCHAR2(50),
    "USE_YN" VARCHAR2(1),
    "REMARK" VARCHAR2(200),
    "REG_ID" VARCHAR2(15),
    "REG_DT" VARCHAR2(14),
    "UPD_ID" VARCHAR2(15),
    "UPD_DT" VARCHAR2(14),
    "REG_DTM" VARCHAR2(20),
    "UPD_DTM" VARCHAR2(20)
);
CREATE UNIQUE INDEX "CM_APPR_ATHR_PK" ON "CM_APPR_ATHR" ("APPR_ATHR_CD");
----COMMENT ADD START----
COMMENT ON TABLE CM_APPR_ATHR IS '청구서' ;

COMMENT ON COLUMN CM_APPR_ATHR.APPR_ATHR_CD IS '회사코드';
COMMENT ON COLUMN CM_APPR_ATHR.APPR_ATHR_NM IS '회계기준코드';
COMMENT ON COLUMN CM_APPR_ATHR.USE_YN IS '회기';
COMMENT ON COLUMN CM_APPR_ATHR.REMARK IS '발생한도';
COMMENT ON COLUMN CM_APPR_ATHR.REG_ID IS '최종한도';
COMMENT ON COLUMN CM_APPR_ATHR.REG_DT IS '생성계정';
COMMENT ON COLUMN CM_APPR_ATHR.UPD_ID IS '생성일자';
COMMENT ON COLUMN CM_APPR_ATHR.UPD_DT IS '생성단말번호';
COMMENT ON COLUMN CM_APPR_ATHR.REG_DTM IS '변경사용자계정';
COMMENT ON COLUMN CM_APPR_ATHR.UPD_DTM IS '변경사용자계정';

DROP TABLE CM_APPR_ATHR;

SELECT * FROM CM_APPR_ATHR;
----COMMENT ADD END----