CREATE TABLE RULE_WHITE_USER
(
    CUST_NO VARCHAR2(256) NOT NULL,
    RUL_CD VARCHAR2(5) NOT NULL,
    STR_DT VARCHAR2(8),
    END_DT VARCHAR2(8),
    PROC_STS VARCHAR2(2),
    USE_YN VARCHAR2(1),
    AGN_USR_ID VARCHAR2(15),
    REASON VARCHAR2(4000),
    REJECT VARCHAR2(4000),
    REG_ID VARCHAR2(15),
    UPD_ID VARCHAR2(15),
    REG_DT VARCHAR2(14),
    UPD_DT VARCHAR2(14)
);
CREATE UNIQUE INDEX RULE_WHITE_USER_PK ON RULE_WHITE_USER (CUST_NO, RUL_CD);
